---
kind: "Alertmanager"
api_family: "monitoring.coreos.com"
default_command: "alertmanagers"
command:
  - "alm"
listview:
  name: "Alertmanagers"
  group: "Observability"
  field_indexes:
    Wide:
      fields: ["namespace", "name", "version",
               "current_replicas", "uptodate_replicas",
               "available_replicas", "unavailable_replicas",
               "condition_reconciled", "condition_available", "paused", "age"]
      sortcolumn: "namespace"
    Normal:
      fields: ["namespace", "name", "version",
               "current_replicas",
               "condition_reconciled", "condition_available", "paused", "age"]
      sortcolumn: "namespace"
  fields:
    available_replicas:
      header: "Available:"
      paths:
        - path: ["status#availableReplicas", "status#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
    condition_available:
      header: "Available:"
      paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
            - key: "type"
              in: "Available"
          default: ["<unknown>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
                - context: "main"
                  type: "status_ok"
            "False":
              field_colors:
                - context: "main"
                  type: "status_not_ok"
            "<unknown>":
              field_colors:
                - context: "types"
                  type: "unset"
    condition_reconciled:
      header: "Reconciled:"
      paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
            - key: "type"
              in: "Reconciled"
          default: ["<unknown>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
                - context: "main"
                  type: "status_ok"
            "False":
              field_colors:
                - context: "main"
                  type: "status_not_ok"
            "<unknown>":
              field_colors:
                - context: "types"
                  type: "unset"
    current_replicas:
      header: "Current:"
      path: "status#replicas"
      type: "int"
      formatter: "numerical"
      align: "right"
    paused:
      header: "Paused:"
      path: "status#paused"
      type: "bool"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
                - context: "main"
                  type: "status_pending"
            "False":
              field_colors:
                - context: "main"
                  type: "status_ok"
    unavailable_replicas:
      header: "Unavailable:"
      path: "status#unavailableReplicas"
      default: 0
      type: "raw"
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_not_ok"
      align: "right"
    uptodate_replicas:
      header: "Up to Date:"
      paths:
        - path: ["status#updatedReplicas", "status#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
    version:
      header: "Version:"
      path: "spec#version"
      default: "<unset>"
      type: "str"
      formatter: "version"
infoview:
  name: "Alertmanager Info"
  infopad:
    row_indexes:
      Normal:
        fields:
          - "image"
          - "external_url"
          - "listen_local"
          - "log_format"
          - "loglevel"
          - "retention"
          - "port_name"
          - "route_prefix"
          - "node_selector"
          - "alertmanager_config_selector"
          - "service_account"
          - "version"
          - "replicas"
          - "paused"
          - "condition_reconciled"
          - "condition_available"
    rows:
      alertmanager_config_selector:
        header: [["AlertManagerConfig Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#alertmanagerConfigSelector#matchLabels"]
            pathtype: "key_value"
            default: ["<unset>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      condition_available:
        header: [["Available:", ["main", "infoheader"]]]
        paths:
          - path: "status#conditions"
            pathtype: "items"
            subpath: "status"
            when:
              - key: "type"
                in: "Available"
            default: ["<unknown>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                  - context: "main"
                    type: "status_ok"
              "False":
                field_colors:
                  - context: "main"
                    type: "status_not_ok"
              "<unknown>":
                field_colors:
                  - context: "types"
                    type: "unset"
      condition_reconciled:
        header: [["Reconciled:", ["main", "infoheader"]]]
        paths:
          - path: "status#conditions"
            pathtype: "items"
            subpath: "status"
            when:
              - key: "type"
                in: "Reconciled"
            default: ["<unknown>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                  - context: "main"
                    type: "status_ok"
              "False":
                field_colors:
                  - context: "main"
                    type: "status_not_ok"
              "<unknown>":
                field_colors:
                  - context: "types"
                    type: "unset"
      external_url:
        header: [["External URL:", ["main", "infoheader"]]]
        path: "spec#externalUrl"
        default: "<unset>"
        type: "str"
        formatter: "address"
      image:
        header: [["Image:", ["main", "infoheader"]]]
        paths:
          - path: "spec#image"
            pathtype: "regex"
            regex: "^([^:]+):(.*)"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "generic"
            - type: "version"
          field_separators:
            - type: "version"
          field_formatters:
            - ""
            - "version"
      listen_local:
        header: [["Listen Local:", ["main", "infoheader"]]]
        path: "spec#listenLocal"
        default: "<unset>"
        type: "bool"
      log_format:
        header: [["Log Format:", ["main", "infoheader"]]]
        path: "spec#logFormat"
        default: "<unset>"
        type: "str"
      loglevel:
        header: [["Loglevel:", ["main", "infoheader"]]]
        path: "spec#logLevel"
        default: "<unset>"
        type: "str"
      node_selector:
        header: [["Node La", ["main", "infoheader"]],
                 ["b", ["main", "infoheader_shortcut"]],
                 ["el Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#nodeSelector"]
            pathtype: "key_value"
            default: ["<unset>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      paused:
        header: [["Paused:", ["main", "infoheader"]]]
        path: "status#paused"
        default: false
        type: "bool"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                  - context: "main"
                    type: "status_pending"
              "False":
                field_colors:
                  - context: "main"
                    type: "status_ok"
      port_name:
        header: [["Port Name:", ["main", "infoheader"]]]
        path: "spec#portName"
        type: "str"
        formatting:
          field_colors:
            - type: "service"
      replicas:
        header: [["Replicas:", ["main", "infoheader"]]]
        paths:
          - path: [["status#replicas"], " Current",
                   ["status#availableReplicas"], " Available",
                   ["status#updatedReplicas"], " Up to Date",
                   ["status#unavailableReplicas"], " Unavailable"]
            pathtype: "tuple"
            default: [0, "", 0, "", 0, ""]
        formatter: "list"
        formatting:
          field_colors:
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
          field_separators:
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
      retention:
        header: [["Retention:", ["main", "infoheader"]]]
        path: "spec#retention"
        type: "str"
        formatter: "age"
      route_prefix:
        header: [["Route Prefix:", ["main", "infoheader"]]]
        path: "spec#routePrefix"
        default: "<unset>"
        type: "str"
      service_account:
        header: [["S", ["main", "infoheader_shortcut"]],
                 ["ervice Account:", ["main", "infoheader"]]]
        path: "spec#serviceAccountName"
        default: "<unset>"
        type: "str"
      version:
        header: [["Version:", ["main", "infoheader"]]]
        path: "spec#version"
        default: "<unset>"
        type: "str"
        formatter: "version"
  listpad:
    listgetter: "generic_listgetter"
    listgetter_args:
      _kind: "Pod"
      _label_selector_path: "spec#selector"
      _none_on_empty_selector: true
    infogetter: "generic_infogetter"
    on_activation:
      call: "resourceinfodispatch"
      kind: "Pod"
    field_indexes:
      Wide:
        fields: ["namespace", "name", "pod_status", "node_name",
                 "pod_ip", "age", "restarts", "last_restart", "containers"]
        sortcolumn: "pod_status"
      Normal:
        fields: ["namespace", "name", "pod_status", "node_name", "age",
                 "restarts", "last_restart"]
        sortcolumn: "pod_status"
      Compact:
        fields: ["namespace", "name", "pod_status", "age", "restarts",
                 "last_restart"]
        sortcolumn: "pod_status"
    fields:
      containers:
        header: "Containers:"
        paths:
          - paths:
              - "spec#initContainers"
              - "spec#containers"
            pathtype: "items"
            subpaths:
              - "name"
              - subpath: "image"
                regex: ["^.+/[^:^/]+:(.+?)@.*", "^.+/[^:^/]+:(.+)"]
            type: "raw"
        formatter: "list"
        formatting:
          field_colors:
            - type: "generic"
            - type: "version"
          field_separators:
            - type: "version"
          field_formatters:
            - ""
            - "version"
      last_restart:
        header: "Latest Restart:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: ["state#running#startedAt",
                      "lastState#terminated#finishedAt"]
            when:
              - key: "restartCount"
                gt: 0
            action: "latest"
            type: "timestamp"
        default: -1
        formatter: "age"
        align: "right"
      node_name:
        header: "Node:"
        path: "spec#nodeName"
        type: "host"
        default: "<none>"
        formatting:
          field_colors:
            - type: "host"
      pod_ip:
        header: "Pod IP:"
        path: "status#podIP"
        default: "<unset>"
        type: "address"
        formatter: "address"
      restarts:
        header: "Restarts:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: "restartCount"
            action: "sum"
            type: "int"
        default: 0
        formatter: "numerical"
        align: "right"
  shortcuts:
    "Node Label Selector":
      key: "b"
      read_only: true
      helptext: "Show Node label selector"
      widget: "windowwidget"
      widget_args:
        title: "Node Label Selector:"
        headers: ["Key:", "Value:"]
        itemgetter: "get_key_value"
        itemgetter_args:
          path: "spec#nodeSelector"
    "Service Account":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Service Account"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "ServiceAccount"
        namespace_path: "metadata#namespace"
        name_path: "spec#serviceAccountName"
    "Containers":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "List containers"
      widget: "windowwidget"
      widget_args:
        title: "Containers:"
        selectable: true
        itemgetter: "get_list_fields"
        itemgetter_args:
          path: "spec#containers"
          fields:
            - "name"
          pass_ref: true
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Container Information"
        _named_title: true
        _name_path: "name"
    "Show affinities":
      key: "a"
      modifier: "shift"
      read_only: true
      helptext: "Show affinities"
      widget: "windowwidget"
      widget_args:
        headers: ["Type:", "Scheduling:", "Execution:",
                  "Selector:", "Topology:"]
        itemgetter: "get_affinity"
        # This isn't supported for now
        sortcolumn: "type"
