---
kind: "APIServer"
api_family: "config.openshift.io"
default_command: "apiservers.config.openshift.io"
command:
  - "apiservers.config"
  - "apiserver.config"
listview:
  name: "API Servers"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "API Server Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["client_ca", "audit_profile",
                 "encryption_type", "tls_security_profile"]
    rows:
      audit_profile:
        header: [["Audit Profile:", ["main", "infoheader"]]]
        path: "spec#audit#profile"
        type: "str"
      client_ca:
        header: [["Client C", ["main", "infoheader"]],
                 ["A", ["main", "infoheader_shortcut"]],
                 [":", ["main", "infoheader"]]]
        path: "spec#clientCA#name"
        default: "<none>"
        type: "str"
      encryption_type:
        header: [["Encryption Type:", ["main", "infoheader"]]]
        path: "spec#encryption#type"
        default: "<default>"
        type: "str"
      tls_security_profile:
        header: [["TLS Security Profile:", ["main", "infoheader"]]]
        path: "spec#tlsSecurityProfile#type"
        default: "<default>"
        type: "str"
  shortcuts:
    "Owner References":
      key: "o"
      modifier: "shift"
      read_only: true
      helptext: "List Owner References"
      widget: "windowwidget"
      title: "Owner References:"
      selectable: true
      headers: ["Kind:", "API-Version:", "Name:"]
      itemgetter: "get_list_fields"
      itemgetter_args:
        path: "metadata#ownerReferences"
        fields:
          - "kind"
          - "apiVersion"
          - "name"
      # This isn't supported for now
      sortcolumn: "kind"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind_path: 0
        api_version_path: 1
        name_path: 2
        _parent_namespace_path: "metadata#namespace"
    "Additional CORS Allowed Origins":
      key: "o"
      modifier: "shift"
      read_only: true
      helptext: "List additional CORS allowed origins"
      widget: "windowwidget"
      title: "CORS allowed origins:"
      selectable: true
      itemgetter: "get_list_as_list"
      itemgetter_args:
        paths: ["spec#additionalCORSAllowedOrigins"]
      # Not supported for now
      sortcolumn: "origin"
    "Client CA":
      key: "a"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for client CA"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace: "openshift-config"
        name_path: "spec#clientCA#name"
        kind: "ConfigMap"
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
    "View serving certs":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "View serving TLS certificates"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Service TLS certificates"
        _pass_obj: true
        path: "spec#servingCerts"
