---
kind: "BundleDeployment"
api_family: "fleet.cattle.io"
default_command: "bundledeployments.fleet.cattle.io"
command:
  - "bundledeployments.cattle"
  - "bundledeployment.cattle"
  - "bundledeploys.cattle"
  - "bundledeploy.cattle"
  - "bundledeps.cattle"
  - "bundledep.cattle"
listview:
  name: "Bundle Deployments"
  group: "Rancher"
  field_indexes:
    Wide:
      fields: ["namespace", "name", "default_namespace",
               "deployed", "monitored", "desired", "ready", "state", "age"]
    Normal:
      fields: ["namespace", "name", "default_namespace",
               "deployed", "monitored", "state", "age"]
  fields:
    default_namespace:
      header: "Default Namespace:"
      path: "spec#options#defaultNamespace"
      type: "str"
      formatting:
        field_colors:
          - type: "namespace"
    deployed:
      header: "Deployed:"
      path: "status#display#deployed"
      type: "bool"
    desired:
      header: "Desired:"
      path: "status#resourceCounts#desiredReady"
      default: 0
      type: "int"
      formatter: "numerical"
      align: "right"
    monitored:
      header: "Monitored:"
      path: "status#display#monitored"
      type: "bool"
    ready:
      header: "Ready:"
      paths:
        - path: ["status#resourceCounts#ready",
                 "status#resourceCounts#desiredReady"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
    state:
      header: "State:"
      path: "status#display#state"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            NotReady:
              field_colors:
                - context: "main"
                  type: "status_not_ok"
            Ready:
              field_colors:
                - context: "main"
                  type: "status_ok"
infoview:
  name: "Bundle Deployment Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["release", "default_namespace",
                 "deployment_id",
                 "deployed", "monitored",
                 "resources_header",
                 "resources_desired",
                 "resources_ready",
                 "state"]
    rows:
      default_namespace:
        header: [["D", ["main", "infoheader_shortcut"]],
                 ["efault Namespace:", ["main", "infoheader"]]]
        path: "spec#options#defaultNamespace"
        type: "str"
        formatting:
          field_colors:
            - type: "namespace"
      deployed:
        header: [["Deployed:", ["main", "infoheader"]]]
        path: "status#display#deployed"
        type: "bool"
      deployment_id:
        header: [["Deployment ID:", ["main", "infoheader"]]]
        paths:
          - path: ["status#appliedDeploymentID", "spec#deploymentID"]
            pathtype: "value"
        default: "<unset>"
        type: "str"
      monitored:
        header: [["Monitored:", ["main", "infoheader"]]]
        path: "status#display#monitored"
        type: "bool"
      release:
        header: [["Release:", ["main", "infoheader"]]]
        path: "status#release"
        type: "str"
      resources_desired:
        header: [["  Desired:", ["main", "infoheader"]]]
        path: "status#resourceCounts#desiredReady"
        default: 0
        type: "int"
        formatter: "numerical"
      resources_header:
        header: [["Resources:", ["main", "infoheader"]]]
      resources_ready:
        header: [["  Ready:", ["main", "infoheader"]]]
        paths:
          - path: ["status#resourceCounts#ready",
                   "status#resourceCounts#desiredReady"]
            pathtype: "comparison"
            default: [0, 0]
        formatter: "value_mapper"
        formatting:
          mapping:
            ranges:
              - min: 0
                max: 1
                field_colors:
                  - context: "main"
                    type: "status_ok"
              - default: true
                field_colors:
                  - context: "main"
                    type: "status_pending"
      state:
        header: [["State:", ["main", "infoheader"]]]
        path: "status#display#state"
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              NotReady:
                field_colors:
                  - context: "main"
                    type: "status_not_ok"
              Ready:
                field_colors:
                  - context: "main"
                    type: "status_ok"
  shortcuts:
    "Open default Namespace":
      key: "d"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for default Namespace"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        name_path: "spec#options#defaultNamespace"
        kind: "Namespace"
