---
kind: "CDIConfig"
api_family: "cdi.kubevirt.io"
default_command: "cdiconfigs"
listview:
  name: "CDI Configs"
  group: "Storage & Backups"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "CDI Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["controller", "feature_gates", "tls_security_profile_type",
                 "import_proxy_header",
                 "import_proxy_http_proxy",
                 "import_proxy_https_proxy",
                 "import_proxy_no_proxy",
                 "import_proxy_trusted_ca_proxy",
                 "upload_proxy_url_override", "scratch_space_storage_class",
                 "filesystem_overhead_header",
                 "filesystem_overhead_global",
                 "filesystem_overhead_storage_class"]
    rows:
      controller:
        header: [["C", ["main", "infoheader_shortcut"]],
                 ["ontroller:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "kind"
              - "apiVersion"
              - "name"
            when:
              - key: "controller"
                eq: true
            type: ["kind", "api_group", "name"]
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "kind"
            - type: "api_group"
            - type: "generic"
          field_separators:
            - type: "kind_api_group"
            - type: "kind"
      feature_gates:
        header: [["Feature Gates:", ["main", "infoheader"]]]
        path: "spec#featureGates"
        default: ["<none>"]
        type: "raw"
        formatter: "list"
      filesystem_overhead_global:
        header: [["  Global:", ["main", "infoheader"]]]
        path: "status#filesystemOverhead#global"
        default: "<none>"
        type: "str"
        formatter: "numerical"
      filesystem_overhead_header:
        header: [["Filesystem Overhead:", ["main", "infoheader"]]]
      filesystem_overhead_storage_class:
        header: [["  Storage Class:", ["main", "infoheader"]]]
        paths:
          - path: "status#filesystemOverhead#storageClass"
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "numerical"
          field_formatters:
            - ""
            - "numerical_with_units"
          field_separators:
            - type: "keyvalue"
      import_proxy_header:
        header: [["Import Proxy:", ["main", "infoheader"]]]
      import_proxy_http_proxy:
        header: [["  HTTP Proxy:", ["main", "infoheader"]]]
        path: "status#importProxy#HTTPProxy"
        fallback_on_empty: true
        default: "<none>"
        type: "str"
      import_proxy_https_proxy:
        header: [["  HTTPS Proxy:", ["main", "infoheader"]]]
        path: "status#importProxy#HTTPSProxy"
        fallback_on_empty: true
        default: "<none>"
        type: "str"
      import_proxy_no_proxy:
        header: [["  No Proxy:", ["main", "infoheader"]]]
        path: "status#importProxy#noProxy"
        fallback_on_empty: true
        default: "<none>"
        type: "str"
      import_proxy_trusted_ca_proxy:
        header: [["  Trusted CA Proxy:", ["main", "infoheader"]]]
        path: "status#importProxy#trustedCAProxy"
        fallback_on_empty: true
        default: "<none>"
        type: "str"
      scratch_space_storage_class:
        header: [["Scratch Space ", ["main", "infoheader"]],
                 ["S", ["main", "infoheader_shortcut"]],
                 ["torage Class:", ["main", "infoheader"]]]
        path: "status#scratchSpaceStorageClass"
        default: "<unset>"
        type: "str"
      tls_security_profile_type:
        header: [["TLS Security Profile Type:", ["main", "infoheader"]]]
        path: "spec#tlsSecurityProfile#type"
        default: "<unset>"
        type: "str"
      upload_proxy_url_override:
        header: [["Upload Proxy URL Override:", ["main", "infoheader"]]]
        path: "spec#uploadProxyURLOverride"
        default: "<unset>"
        type: "str"
  shortcuts:
    "Open controller":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for controller"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace_path: "metadata#namespace"
        owner_reference_path: "metadata#ownerReferences"
    "Open Scratch Space Storage Class":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for scratch space Storage Class"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "StorageClass"
        api_family: "storage.k8s.io"
        name_path: "status#scratchSpaceStorageClass"
    "Show proxy settings":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "Show proxy settings"
      widget: "windowwidget"
      title: "Proxy settings:"
      headers: ["Protocol:", "URL:"]
      itemgetter: "get_key_value"
      itemgetter_args:
        path: "status#importProxy"
      # Not supported for now
      sortcolumn: "protocol"
    "Show Requests":
      key: "e"
      modifier: "shift"
      read_only: true
      helptext: "Show requests"
      title: "Requests:"
      widget: "windowwidget"
      headers: ["Resource:", "Request:", "Limit:"]
      itemgetter: "get_resource_list"
      itemgetter_args:
        allocatable_path: "status#defaultPodResourceRequirements#requests"
        capacity_path: "status#defaultPodResourceRequirements#limits"
      formatting: [["windowwidget", "default"],
                   ["windowwidget", "highlight"],
                   ["windowwidget", "highlight"]]
      # Not supported for now
      # This isn't supported for now
      sortcolumn: "requests"
