---
kind: "Console"
api_family: "config.openshift.io"
default_command: "consoles.config.openshift.io"
command:
  - "consoles.config"
  - "console.config"
listview:
  name: "Consoles"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Console Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["console_url"]
    rows:
      console_url:
        header: [["Console ", ["main", "infoheader"]],
                 ["U", ["main", "infoheader_shortcut"]],
                 ["RL:", ["main", "infoheader"]]]
        path: "status#consoleURL"
        type: "str"
        formatting:
          field_colors:
            - type: "url"
  shortcuts:
    "Open Console":
      key: "u"
      modifier: "shift"
      read_only: true
      helptext: "Open console in browser"
      action: "execute"
      action_args:
        command: ["xdg-open", ["status#consoleURL"]]
