---
kind: "CRIOCredentialProviderConfig"
api_family: "config.openshift.io"
default_command: "criocredentialproviderconfigs"
command:
  - "criocredprovconfs.config"
  - "criocredprovconf.config"
  - "criocredprovconfs"
  - "criocredprovconf"
listview:
  name: "CRIO Credential Provider Configs"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "CRIO Credential Provider Config Info"
  infopad:
