---
kind: "InsightsDataGather"
api_family: "config.openshift.io"
default_command: "insightsdatagathers"
listview:
  name: "Insights Data Gathers"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Insights Data Gather Info"
  infopad:
