---
kind: "Node"
api_family: "config.openshift.io"
default_command: "nodes.config.openshift.io"
command:
  - "nodes.config"
  - "node.config"
listview:
  name: "Nodes"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Node Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cgroup_mode"]
    rows:
      cgroup_mode:
        header: [["CGroup Mode:", ["main", "infoheader"]]]
        path: "spec#cgroupMode"
        default: "<unset>"
        type: "str"
