---
kind: "OLMConfig"
api_family: "operators.coreos.com"
default_command: "olmconfigs"
command:
  - "olmconfs"
  - "olmconf"
listview:
  name: "OLM Configs"
  group: "API & Extendability"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "OLM Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version",
                 "disable_copied_csvs", "package_server_sync_interval"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]],
                 ["V", ["main", "infoheader_shortcut"]],
                 ["ersion:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "name"
            when:
              - key: "kind"
                eq: "ClusterVersion"
        default: "<none>"
      disable_copied_csvs:
        header: [["Disable Copied CSVs:", ["main", "infoheader"]]]
        path: "spec#features#disableCopiedCSVs"
        default: false
        type: "bool"
      package_server_sync_interval:
        header: [["Package Server Sync Interval:", ["main", "infoheader"]]]
        path: "spec#features#packageServerSyncInterval"
        default: "12h"
        type: "str"
        formatter: "numerical"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
