---
kind: "OLMConfig"
api_family: "operators.coreos.com"
default_command: "olmconfigs"
command:
  - "olmconfs"
  - "olmconf"
listview:
  name: "OLM Configs"
  group: "API & Extendability"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "OLM Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["disable_copied_csvs", "package_server_sync_interval"]
    rows:
      disable_copied_csvs:
        header: [["Disable Copied CSVs:", ["main", "infoheader"]]]
        path: "spec#features#disableCopiedCSVs"
        default: false
        type: "bool"
      package_server_sync_interval:
        header: [["Package Server Sync Interval:", ["main", "infoheader"]]]
        path: "spec#features#packageServerSyncInterval"
        default: "12h"
        type: "str"
        formatter: "numerical"
