---
kind: "OperatorHub"
api_family: "config.openshift.io"
default_command: "operatorhubs.config.openshift.io"
command:
  - "operatorhubs.config"
  - "operatorhub.config"
listview:
  name: "Operator Hubs"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Operator Hub Info"
  infopad:
  shortcuts:
    "Show sources":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Show sources"
      widget: "windowwidget"
      title: "Sources:"
      itemgetter: "get_list_fields"
      itemgetter_args:
        path: "status#sources"
        fields:
          - "name"
          - "status"
          - "disabled"
      headers: ["Name:", "Status:", "Disabled:"]
      # Not supported for now
      sortcolumn: "status"
