---
kind: "PrometheusRule"
api_family: "monitoring.coreos.com"
default_command: "prometheusrules"
command:
  - "promrules"
  - "promrule"
listview:
  name: "Prometheus Rules"
  group: "Observability"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "controller", "age"]
      sortcolumn: "namespace"
  fields:
    controller:
      header: "Controller:"
      paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
            - "kind"
            - "apiVersion"
            - "name"
          when:
            - key: "controller"
              eq: true
          type: ["kind", "api_group", "name"]
          default: ["<none>"]
      formatter: "list"
      formatting:
        field_colors:
          - type: "kind"
          - type: "api_group"
          - type: "generic"
        field_separators:
          - type: "kind_api_group"
          - type: "kind"
infoview:
  name: "Prometheus Rule Info"
  # PrometheusRule annotations contains the entire rule set;
  # this is way too much to handle for the annotations widget
  annotations: "null"
  infopad:
    row_indexes:
      Normal:
        fields: ["controller"]
    rows:
      controller:
        header: [["C", ["main", "infoheader_shortcut"]],
                 ["ontroller:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "kind"
              - "apiVersion"
              - "name"
            when:
              - key: "controller"
                eq: true
            type: ["kind", "api_group", "name"]
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "kind"
            - type: "api_group"
            - type: "generic"
          field_separators:
            - type: "kind_api_group"
            - type: "kind"
  listpad:
    listgetter: "listgetter_path"
    listgetter_args:
      path: ""
    infogetter: "get_promrules_info"
    on_activation:
      call: "resourceinfodispatch"
      kind: "__PrometheusRuleData"
      api_family: "monitoring.coreos.com"
    field_indexes:
      Normal:
        fields: ["group", "rtype", "alertrecord", "duration"]
        sortcolumn: "rtype"
    fields:
      alertrecord:
        header: "Name:"
        path: "alertheader"
        type: "str"
      duration:
        header: "Duration:"
        path: "duration"
        type: "raw"
        formatter: "age"
        align: "right"
      group:
        header: "Group:"
        path: "group"
        type: "str"
      rtype:
        header: "Type:"
        path: "rtype"
        type: "str"
  shortcuts:
    "Open controller":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for controller"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace_path: "metadata#namespace"
        owner_reference_path: "metadata#ownerReferences"
