---
kind: "Prometheus"
api_family: "monitoring.coreos.com"
default_command: "prometheuses"
command:
  - "proms"
  - "prom"
listview:
  name: "Prometheuses"
  group: "Observability"
  field_indexes:
    Wide:
      fields: ["namespace", "name", "version",
               "current_replicas", "uptodate_replicas",
               "available_replicas", "unavailable_replicas",
               "paused", "age"]
      sortcolumn: "namespace"
    Normal:
      fields: ["namespace", "name", "version",
               "current_replicas", "paused", "age"]
      sortcolumn: "namespace"
  fields:
    available_replicas:
      header: "Available:"
      paths:
        - path: ["status#availableReplicas", "status#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
    current_replicas:
      header: "Current:"
      path: "status#replicas"
      type: "int"
      formatter: "numerical"
      align: "right"
    paused:
      header: "Paused:"
      path: "status#paused"
      default: false
      type: "bool"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
                - context: "main"
                  type: "status_pending"
            "False":
              field_colors:
                - context: "main"
                  type: "status_ok"
    unavailable_replicas:
      header: "Unavailable:"
      path: "status#unavailableReplicas"
      default: 0
      type: "raw"
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_not_ok"
      align: "right"
    uptodate_replicas:
      header: "Up to Date:"
      paths:
        - path: ["status#updatedReplicas", "status#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
    version:
      header: "Version:"
      path: "spec#version"
      default: "Latest"
      type: "str"
      formatter: "version"
infoview:
  name: "Prometheus Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["image", "external_url",
                 "listen_local", "log_format", "loglevel",
                 "port_name", "service_account", "replicas", "paused"]
    rows:
      external_url:
        header: [["External URL:", ["main", "infoheader"]]]
        path: "spec#externalUrl"
        default: "<unset>"
        type: "str"
        formatter: "uri"
      image:
        header: [["Image:", ["main", "infoheader"]]]
        paths:
          - path: "spec#image"
            pathtype: "regex"
            regex: "^([^:]+):(.*)"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "generic"
            - type: "version"
          field_separators:
            - type: "version"
          field_formatters:
            - ""
            - "version"
      listen_local:
        header: [["Listen Local:", ["main", "infoheader"]]]
        path: "spec#listenLocal"
        default: "<unset>"
        type: "bool"
      log_format:
        header: [["Log Format:", ["main", "infoheader"]]]
        path: "spec#logFormat"
        default: "<unset>"
        type: "str"
      loglevel:
        header: [["Loglevel:", ["main", "infoheader"]]]
        path: "spec#logLevel"
        default: "<unset>"
        type: "str"
      paused:
        header: [["Paused:", ["main", "infoheader"]]]
        path: "status#paused"
        default: false
        type: "bool"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                  - context: "main"
                    type: "status_pending"
              "False":
                field_colors:
                  - context: "main"
                    type: "status_ok"
      port_name:
        header: [["Port Name:", ["main", "infoheader"]]]
        path: "spec#portName"
        type: "str"
        formatting:
          field_colors:
            - type: "service"
      replicas:
        header: [["Replicas:", ["main", "infoheader"]]]
        paths:
          - path: [["status#replicas"], " Current",
                   ["status#availableReplicas"], " Available",
                   ["status#updatedReplicas"], " Up to Date",
                   ["status#unavailableReplicas"], " Unavailable"]
            pathtype: "tuple"
            default: [0, "", 0, "", 0, ""]
        formatter: "list"
        formatting:
          field_colors:
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
          field_separators:
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
      service_account:
        header: [["S", ["main", "infoheader_shortcut"]],
                 ["ervice Account:", ["main", "infoheader"]]]
        path: "spec#serviceAccountName"
        default: "<none>"
        type: "str"
  logpad:
    infogetter: "logpad_formatted"
    infogetter_args:
      formatter: "format_yaml"
      path: "spec"
    timestamps: false
  shortcuts:
    "Service Account":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Service Account"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "ServiceAccount"
        name_path: "spec#serviceAccountName"
        namespace_path: "metadata#namespace"
    "Alertmanager Endpoints":
      key: "e"
      modifier: "shift"
      read_only: true
      helptext: "Show Alertmanager Endpoints information"
      widget: "windowwidget"
      widget_args:
        title: "Alertmanager Endpoints:"
        headers: ["Namespace:", "Name:", "Port:", "Path prefix:"]
        selectable: true
        itemgetter: "get_list_fields"
        itemgetter_args:
          path: "spec#alerting#alertmanagers"
          fields:
            - "namespace"
            - "name"
            - "port"
            - "pathPrefix"
        # Not supported for now
        sortcolumn: "namespace"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        kind: "Endpoints"
        name_path: 1
        namespace_path: 0
    "Resources":
      key: "r"
      modifier: "shift"
      read_only: true
      helptext: "Show resources"
      widget: "windowwidget"
      widget_args:
        title: "Resources:"
        headers: ["Request Type:", "Limits:"]
        formatting: [["windowwidget", "default"],
                     ["windowwidget", "highlight"]]
        itemgetter: "get_key_value"
        itemgetter_args:
          path: "spec#resources"
    "Containers":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "List containers"
      widget: "windowwidget"
      widget_args:
        title: "Containers:"
        selectable: true
        itemgetter: "get_list_fields"
        itemgetter_args:
          path: "spec#containers"
          fields:
            - "name"
          pass_ref: true
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Container Information"
        _named_title: true
        _name_path: "name"
    "Show affinities":
      key: "a"
      modifier: "shift"
      read_only: true
      helptext: "Show affinities"
      widget: "windowwidget"
      widget_args:
        title: "Affinities:"
        headers: ["Type:", "Scheduling:",
                  "Execution:", "Selector:", "Topology:"]
        itemgetter: "get_affinity"
        # This isn't supported for now
        sortcolumn: "type"
