---
kind: "ScrapeConfig"
api_family: "monitoring.coreos.com"
default_command: "scrapeconfigs"
command:
  - "scrapeconfs"
  - "scrapeconf"
listview:
  name: "Scrape Configs"
  group: "Observability"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Scrape Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["authorization", "honor_labels", "metrics_path", "scheme",
                 "tls_config_header", "tls_config_insecure_skip_verify"]
    rows:
      authorization:
        header: [["A", ["main", "infoheader_shortcut"]],
                 ["uthorization:", ["main", "infoheader"]]]
        path: "spec#authorization#credentials#name"
        default: "<none>"
        type: "str"
      honor_labels:
        header: [["Honor Labels:", ["main", "infoheader"]]]
        path: "spec#honorLabels"
        default: "<unset>"
        type: "bool"
      metrics_path:
        header: [["Metrics Path:", ["main", "infoheader"]]]
        path: "spec#metricsPath"
        default: "<unset>"
        type: "str"
        formatting:
          field_colors:
            - type: "path"
      scheme:
        header: [["Scheme:", ["main", "infoheader"]]]
        path: "spec#scheme"
        default: "<unset>"
        type: "str"
      tls_config_header:
        header: [["TLS Config:", ["main", "infoheader"]]]
      tls_config_insecure_skip_verify:
        header: [["  Insecure Skip Verify:", ["main", "infoheader"]]]
        path: "spec#tlsConfig#insecureSkipVerify"
        default: "<unset>"
        type: "bool"
  listpad:
    listgetter: "listgetter_path"
    listgetter_args:
      paths:
        - path: "spec#kubernetesSDConfigs"
          key_name: "type"
          key_value: "Kubernetes"
          type: "list"
        - path: "spec#staticConfigs"
          key_name: "type"
          key_value: "Static"
          type: "list"
        - path: "spec#fileSDConfigs"
          key_name: "type"
          key_value: "File"
          type: "list"
        - path: "spec#httpSDConfigs"
          key_name: "type"
          key_value: "HTTP"
          type: "list"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["type", "role", "namespaces", "labels", "targets", "url",
                 "refresh_interval", "files"]
        sortcolumn: "type"
    fields:
      files:
        header: "Files:"
        path: "files"
        default: ["<unset>"]
        type: "raw"
        formatter: "list"
        formatting:
          field_colors:
            - type: "path"
      namespaces:
        header: "Namespaces:"
        path: "namespaces#names"
        default: ["<unset>"]
        type: "raw"
        formatter: "list"
        formatting:
          field_colors:
            - type: "namespace"
      labels:
        header: "Labels:"
        paths:
          - path: ["labels"]
            pathtype: "key_value"
        default: ["<unset>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      refresh_interval:
        header: "Refresh Interval:"
        path: "refreshInterval"
        default: "<unset>"
        type: "str"
        formatter: "numerical"
      role:
        header: "Role:"
        path: "role"
        default: "<unset>"
        type: "str"
      targets:
        header: "Targets:"
        path: "targets"
        default: ["<unset>"]
        type: "raw"
        formatter: "list"
      type:
        header: "Type:"
        path: "type"
        default: "<unset>"
        type: "str"
      url:
        header: "URL:"
        path: "url"
        default: "<unset>"
        type: "raw"
        formatter: "uri"
  shortcuts:
    "Authorization":
      key: "a"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for authorization"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Secret"
        name_path: "spec#authorization#credentials#name"
        namespace_path: "metadata#namespace"
